on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Test
      run: go test -v ./createdirs