on:
  push:
    tags:
      - "v*.*.*"

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: Build and release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Build Windows 64
      run: go build -v -o build/ ./...

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/*
